p3: main.cpp l_enlazada.cpp nodo.cpp vector.cpp stack.cpp queue.cpp complejo.cpp entero.cpp flotante.cpp natural.cpp racional.cpp
	g++ -Wall main.cpp l_enlazada.cpp nodo.cpp vector.cpp stack.cpp queue.cpp complejo.cpp entero.cpp flotante.cpp natural.cpp racional.cpp -o ../bin/p3; \
	cd ../bin; \
	./p3;
